SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

PLAYER_SHOOT_SPEED = 500

SHOT_RADIUS = 5

PLAYER_SHOOT_COOLDOWN = 0.3

ASTEROID_MIN_VALUE=50
ASTEROID_MED_VALUE=20
ASTEROID_MAX_VALUE=10

TEXT_FONT="Ariel"

HEART_PADDING_x=-90
HEART_PADDING_y=-5
PLAYER_MAX_LIVES=3
